ontentdir: "content"
layoutdir: "layouts"
publishdir: "public"
indexes:
    category: "categories"
baseURL: "http://simplybinary.github.io"
title: "Simply Binary"
canonifyURLs: true
metaDataFormat:: "yaml"
menu:
  main:
    - Name: "Home"
      Weight: 1
      Identifier: "home"
      URL: "#"
    - Name: "Process"
      Weight: 2
      Identifier: "process"
      URL: "#process"
    - Name: "Services"
      Weight: 3
      Identifier: "services"
      URL: "#services"
    - Name: "Work"
      Weight: 4
      Identifier: "work"
      URL: "#work"
    - Name: "Team"
      Weight: 5
      Identifier: "team"
      URL: "#team"
    - Name: "Blog"
      Weight: 6
      Identifier: "blog"
      URL: "http://blog.simplybinary.com"
  social:
    - Name: "Facebook"
      Weight: 10
      Identifier: "facebook"
      URL: "/"
    - Name: "Twitter"
      Weight: 20
      Identifier: "twitter"
      URL: "/"
    - Name: "RSS"
      Weight: 30
      Identifier: "rss"
      URL: "/"
params:
  BlogURL: "http://blog.simplybinary.com"
